export const constants = {
    name: "Roughbook",
    categories: [
        "Rent",
        "Grocery",
        "Food",
        "Transport",
        "Shopping",
        "Utilities",
        "Electricity",
        "Water Bill",
        "Gas",
        "Internet",
        "Phone",
        "Insurance",
        "Healthcare",
        "Doctor",
        "Pharmacy",
        "Subscriptions",
        "Entertainment",
        "Movies",
        "Travel",
        "Gifts",
        "Donations",
        "Education",
        "Tuition",
        "Childcare",
        "Household",
        "Pet Care",
        "Loan Payment",
        "EMI",
        "Credit Card",
        "Investment",
        "Miscellaneous",
        "Other",
        "Salary",
        "Freelance",
        "Bonus",
        "Interest",
        "Dividends",
        "Gifts Received",
        "Refunds",
        "Rental Income",
        "Business Income",
        "Other Income",
        "Debt Payment",
        "Debt Received",
        "Savings",
        "Investment Deposit",
        "Cash Withdrawal",
        "Bank Transfer",
    ]
      
}